language: csharp

sudo: required  # may be able to use the new container-based Travis infrastructure 

services:
  - docker
dist: xenial

#dotnet >2.2.* currently fail on unpack
dotnet: 2.1.302

script:
  - ./build.sh BuildNetFramework

branches:
 only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?/

deploy:
  provider: script
  script: >-
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
    docker build --tag ifsharp/ifsharp:$TRAVIS_TAG . &&
    docker tag ifsharp/ifsharp:$TRAVIS_TAG ifsharp/ifsharp:latest &&
    docker push ifsharp/ifsharp:$TRAVIS_TAG &&
    docker push ifsharp/ifsharp:latest
  on:
    tags: true

