language: csharp

sudo: required

services:
  - docker

script:
  - ./build.sh

branches:
 only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?/

deploy:
  provider: script
  script: >-
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
    docker build --tag ifsharp/ifsharp:$TRAVIS_TAG . &&
    docker tag ifsharp/ifsharp:$TRAVIS_TAG ifsharp/ifsharp:latest &&
    docker push ifsharp/ifsharp:$TRAVIS_TAG &&
    docker push ifsharp/ifsharp:latest
  on:
    tags: true
