# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: fake.sh build --target All
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - bash: . '$(Build.SourcesDirectory)/fake.sh' build --target BuildNetCore
- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - bash: . '$(Build.SourcesDirectory)/fake.sh' build --target BuildNetCore

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
